### PR TITLE
Add media close hook

### PR DESCRIPTION
**Pull request by cyruscollier**
Addresses Issue #785.

### CODE REVIEW

**Review by goldenapples — APPROVED** [review]
Looks good to me - thanks for the PR!

We have some other hooks - specifically `render_destroy` that I was considering suggesting that you reuse for this purpose. But its better not to break any existing usage, in case any developers are using the render_destroy hook and depending on its current (buggy) behavior of only being triggered when a shortcode is sent to the editor.

So I think this can be merged as is - `render_closed` is a clear hook name, and I'll add a note in the `render_destroy` docblock clarifying that this hook is only run on inserting a shortcode.

**Comment by desaiuditd** [comment]
@goldenapples  What event would you recommend to use on updating existing shortcode ? Would it still be `render_closed`?

> So I think this can be merged as is - render_closed is a clear hook name, and I'll add a note in the render_destroy docblock clarifying that this hook is only run on inserting a shortcode.

**Comment by desaiuditd** [comment]
Apparently, while digging in further, I realised that the `render_destroy` not being triggered on close, could be because of https://github.com/wp-shortcake/shortcake-bakery/issues/219

https://github.com/wp-shortcake/shortcake-bakery/pull/220 solves the issue and supersedes this PR. 

@goldenapples Thoughts?

**Comment by goldenapples** [comment]
Thanks @cyruscollier for the PR and @desaiuditd for testing... Merging this PR now.

**Pull request merged**
