### PR TITLE
Offer a `register_shortcode_ui` hook for plugins to register on

### PR DESCRIPTION
**Pull request by danielbachhuber**
See #385

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@goldenapples how do you feel about this?

**Comment by goldenapples** [comment]
This doesn't seem like it addresses the issue @jrfnl raised, as the shortcode ui is still being registered on `init`; which includes all front- and back-end views.

What about firing the `register_shortcode_ui` action inside of the `action_admin_enqueue_scripts()` function? That seems to be the only context you'd need shortcode UI registered for, and I believe that's early enough to hook in and register scripts and styles...?

**Comment by danielbachhuber** [comment]
Shouldn't you be able to use shortcode UI on the frontend?

**Comment by danielbachhuber** [comment]
I suppose we could somehow hook into when `wp_editor()` is called.

**Comment by goldenapples** [comment]
... which would be `wp_enqueue_editor`, no? Sorry, I suggested the wrong function. `action_enqueue_wp_editor` would be a more appropriate place to fire the hook.

**Comment by jrfnl** [comment]
Nice ;-)
Maybe update the dev.php example code to mirror the new implementation ?

**Comment by danielbachhuber** [comment]
Closing in favor of #429

**Pull request closed without merging**
