### PR TITLE
Fix coding standards. Remove redundant escaping - late escaping on ou…

### PR DESCRIPTION
**Pull request by dashaluna**
…tput

### CODE REVIEW

**Comment by dashaluna** [comment]
@mattheu if you have time, have a look at this one :)

**Comment by mattheu** [comment]
Thanks Dasha. I agree that escaping should be done as late as possible, but this extra escaping is not really doing any harm. 

It was added here https://github.com/wp-shortcake/shortcake/commit/586c55fad16a14769fc1bcf22e81ea1044379fc7, and the commit doesn't give much info and I don't really remember the background - but I have a reccolection that this may have been requested by VIP. If that's the case, I think its best kept in place.

**Comment by dashaluna** [comment]
@mattheu How can we check with VIP? Late escaping is in accordance to VIP standards. It would be great to promote that as much as possible. Even if there is no real harm with things as they are at the moment, that shouldn't be the reason stopping us from improving it :) Given this is example usage, people are likely to copy it over and cary on with that escaping.

**Comment by dashaluna** [comment]
@mattheu I just realised that we might  be talking about different things. I'm talking about coding standards and html escaping. You mentioned `encoding` in the link in previous comment :) That's different.

This PR is just cleaning up the Coding Standards.

**Comment by mattheu** [comment]
Oh I think I liked to the wrong commit 😀

**Comment by mattheu** [comment]
I'm going to take a look into this - I do wonder if there was some reason behind this early escaping.

**Comment by dashaluna** [comment]
@mattheu thank you! Keep me posted.

**Comment by dashaluna** [comment]
@mattheu any news? ;)

**Comment by mattheu** [comment]
The only thing I can think of is that we are NOT escaping some things on output. Specifically, the label and descriptions in our JS templates. This is done in order to allow HTML such as `<b> and <a href="#">` in the descriptions.

Now we are manually sanitizing these strings using wp_kses_post here: https://github.com/wp-shortcake/shortcake/blob/master/inc/class-shortcode-ui.php#L131 but perhaps this is an extra safety measure.

They're not doing any harm I don't think. Interested if anyone else has any thoughts.

**Comment by goldenapples** [comment]
There was some discussion with VIP about this - see #242 - and they were OK with not escaping these fields on output. Since they're not not being late-escaped, we wanted to escape these fields on marking for i18n - otherwise translators could add HTML tags in translation which might break expected output.

**Comment by mattheu** [comment]
I'm going to close this pull request. The small whitespace fixes were hit as part of https://github.com/wp-shortcake/shortcake/pull/613

**Comment by dashaluna** [comment]
Sad face :( The point of the standards then if VIP selectively approves some exceptions...

**Pull request closed without merging**
