### PR TITLE
Use core's regex for parsing shortcodes

### PR DESCRIPTION
**Pull request by danielbachhuber**
See #392

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@goldenapples @nikolov-tmw Can you look at the JS test failures and let me know what you think? It seems like core's regex provides different behavior than we want.

**Comment by goldenapples** [comment]
> It seems like core's regex provides different behavior than we want.

Looks to me like the problem in tests is in the memoization of the regex in core; that the return value of `wp.shortcode.regexp` is cached from the first time it's run in the test suite, and so later tests that use shortcode tags which weren't defined at first fail.

If you try unwrapping the `_.memoize` call from around the body of `wp.shortcode.regexp`, everything passes... **except** the "parses shortcode with unquoted attributes" test, which is apparently not supported in core.

**Comment by danielbachhuber** [comment]
> Looks to me like the problem in tests is in the memoization of the regex in core; that the return value of wp.shortcode.regexp is cached from the first time it's run in the test suite, and so later tests that use shortcode tags which weren't defined at first fail.

Huh. Ideas on how we can work around it?

**Comment by danielbachhuber** [comment]
@goldenapples #reviewmerge

**Pull request merged**
