### PR TITLE
Fix iframes 2

### PR DESCRIPTION
**Pull request by mattheu**
The issue is that shortcodes that contain JS were not getting sandboxed. #195

This is a half-revert of #143 - and fixes the immediate issue.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Thanks @mattheu — really appreciate it.

Out of curiosity, did you figure out why my PR didn't work?

**Comment by danielbachhuber** [comment]
This PR has a bug where the shortcode is added again if you edit it

**Comment by danielbachhuber** [comment]
But this is just for content that's been iframed.

**Comment by mattheu** [comment]
These damn iframes...

I tried reverting back to 18f2bdde3a13e64fbd5df31b48c67c917b1caa90 to check it was working then - and I think this problem has been present all along.

**Comment by danielbachhuber** [comment]
Hm, pretty sure we had fixed it?

**Comment by danielbachhuber** [comment]
> and I think this problem has been present all along.

Just tested again. Guess it was a bug before :( #202

Thanks for your work on this, @mattheu

**Pull request merged**
