### PR TITLE
Use select2.full.js for compatibility with other plugins which enqueue it

### PR DESCRIPTION
**Pull request by goldenapples**
Built on top of #664.

This adds the check for the SCRIPT_DEBUG constant back in, to load a minified version of select2.full.js unless SCRIPT_DEBUG is true.

### CODE REVIEW

**Comment by goldenapples** [comment]
@mladjom Can you check if this works for you with WooCommerce?

**Comment by mladjom** [comment]
It's good to have this check for loading a minified versions. However while WooCommerce product screen is not locked anymore search under the tab linked products is not working nor select fields under the WooCommerce settings. Real problem is that WooCommerce uses 2.5.3 version of select2 and I didn't find out that they are planing on any update to 4.0.x

**Comment by goldenapples** [comment]
Hmm. That does seem to be a bit of a problem.

To hack around the issue, you can always unregister the version of the select2 js and css files that Shortcake registers on those product pages and register the versions which WooCommerce uses you need registers - as you were doing. But doing this would break any shortcode forms that use select2, or any other plugins that use the latest version of the library.

This PR seems to fix the compatibility issue with Customize Posts (#662) for me - if someone else can confirm that, I'd appreciate it.

But I'm not sure what to do about compatibility with plugins like Woo that use an older version of the library.

**Comment by mladjom** [comment]
Yes, issue with Customize Posts is fixed. 
I don't see a good solution for WooCommerce with select2. How about alternative to select2 like chosen?

**Comment by grappler** [comment]
I have a similar issue with CMB which is using an older version. https://github.com/humanmade/Custom-Meta-Boxes/issues/363

I am just going to test the effect of using the full version will report back here. It may be good to add a check `if ( wp_script_is( 'select2' ) ) {` if there is another script is enqueued.

**Review by mattheu — APPROVED** [review]
👍

**Pull request merged**
