### PR TITLE
Set defaults for inner_content

### PR DESCRIPTION
**Pull request by jitendraharpalani58**
See #237

### CODE REVIEW

**Comment by jitendraharpalani58** [comment]
@collizo4sky

Verify this solution please.

**Comment by jitendraharpalani58** [comment]
@mattheu will you be able to push this to VIP post verification?

**Comment by mattheu** [comment]
Looks good :+1:

**Comment by w3guy** [comment]
@jitendraharpalani58 update fixed the problem. working perfectly. You guys should push the update to WordPress.org repo.

**Comment by mattheu** [comment]
I'll do a release later this week!

**Comment by w3guy** [comment]
#238 ##Bug Alert

inner_content textarea appear on the dialog of shortcode that originally do not support or include the inner_text content.

Eg i have a shortcode with no attribute.. prior to this commit, the dialog becomes blank which is expected but after this comment, inner_text textarea appears on `all` shortcodes regardless of whether it is needed or not.

bug

cc @jitendraharpalani58 @mattheu

**Comment by danielbachhuber** [comment]
Bump @mattheu @joehoyle

Also, when you merge pull requests, please make sure they're filed against a milestone. Release notes and reviewing what changed is painful otherwise.

**Comment by danielbachhuber** [comment]
Previously #204

**Pull request merged**
