### PR TITLE
Expose EditShortcodeForm View for reuse markup.

### PR DESCRIPTION
**Pull request by rahulsprajapati**
Expose EditShortcodeForm View for reuse markup. i.e., in repeater field.
issue: #773

### CODE REVIEW

**Comment by rahulsprajapati** [comment]
**FYI**: the travis-ci failed because of latest WPCS. I suppose all the other PR also have the same issue. https://travis-ci.org/wp-shortcake/shortcake/jobs/309615185

**Comment by rahulsprajapati** [comment]
Fixed phpcs issues: https://github.com/wp-shortcake/shortcake/pull/784

**Comment by rahulsprajapati** [comment]
@goldenapples #784 is merged, you can check this one now. Thanks! :)

**Comment by goldenapples** [comment]
Looks good! Merging...

**Pull request merged**
