### PR TITLE
Debug ajax request when other plugins already add a get parameter to ajaxurl

### PR DESCRIPTION
**Pull request by Vaince**
Hello,

This pull request checks if ajaxurl already contains get parameters that can be added by other plugins (such as WPML).

Xoxo.
Vaince.

### CODE REVIEW

**Comment by goldenapples** [comment]
Interesting. What do these additional query parameters do?

I'm wondering if it makes sense to build the ajax endpoint ourselves and pass it through the localization object so that it was available as something like `shortcodeUIData.endpoints.bulk_do_shortcode`, rather than relying on WP's `ajaxurl` variable.

**Comment by danielbachhuber** [comment]
> ajaxurl already contains get parameters that can be added by other plugins (such as WPML).

I think this is a problem of WPML, and not something Shortcake should be expected to fix.

**Comment by goldenapples** [comment]
I'd like to test including the `action` parameter in the POST body rather than building out the URL to it ourselves. That should fix the use case mentioned here - and when we update to using a REST endpoint for previews, it'll be a non-issue anyways.

**Comment by goldenapples** [comment]
Closing this in favor of #653, which should address the same issue using core functionality.

**Pull request closed without merging**
