### PR TITLE
Abstract Shortcode JS to MVC

### PR DESCRIPTION
**Pull request by jitendraharpalani58**
See #142 

@noppanit Can you help me setup `browserify` when you get a chance ?

### CODE REVIEW

**Comment by noppanit** [comment]
@jitendraharpalani58 I believe it's fixed already. Please try again. Also you need to run `npm install` again to install all the dependencies. I had to fix version of Remapify because the issue in the latest version.

**Comment by jitendraharpalani58** [comment]
@danielbachhuber 
Abstraction is done. 

One thing which is remaining is if someone wants to extend `shortcake` functionality, will they be using browserify? For example, like we did for `select2ui` by extending `sui.views.editAttributeField`. 

There are two ways
- I can still store everything in `sui = window.Shortcode_UI = {}` like we had earlier
- User may choose to use browserify and require the view they want to extend. 
  in our case it would be something like: 

```
var EditAttributeField = require('sui-views/edit-attribute-field');

var blah = EditAttributeField.extend...
```

What do you  suggest?

**Comment by jitendraharpalani58** [comment]
@mattheu @noppanit 
Can you guys review this PR please.

**Comment by danielbachhuber** [comment]
@jitendraharpalani58 Can you merge master so this merges cleanly?

**Comment by jitendraharpalani58** [comment]
@danielbachhuber @mattheu @noppanit 
I added `sui` global variable. I am still using same naming conventions for the constructor as they were to support backward compatibility. Otherwise, it will break for the users who are using our plugin. 

Please review. This should be good to push live.

**Pull request merged**
