### PR TITLE
Add js documentation for `utils/` files

### PR DESCRIPTION
**Pull request by goldenapples**
- Adds jsdoc docblocks for each of the methods in `shortcodeViewConstructor` and `Fetcher`.
- Cleans up and standardizes whitespace in these files according to WordPress coding guidelines.

Part of #16.

### CODE REVIEW

**Comment by goldenapples** [comment]
I think this is a start for these files, though there are a few places where I'm still not understanding jsdoc and might not understand what I'm doing with the types, especially. 

I didn't go through and document the 4.2 compatability functions, just the functionality interfacing with the current core API.  

I also didn't really rewrite any code, though I did find places where callbacks could stand to be cleaned up and duplicate code removed. I'll do that separately from this pull.

Can I get a review of this so I can know whether this is correct & helpful?

**Comment by danielbachhuber** [comment]
:shipit:

Perfect is the enemy of good enough

**Comment by goldenapples** [comment]
> Perfect is the enemy of good enough

haha, true. Do you want to ship #513 while I'm at it?

**Comment by danielbachhuber** [comment]
I'll do another pass at it first.

**Pull request merged**
