### PR TITLE
4.2 compatability

### PR DESCRIPTION
**Pull request by mattheu**
Fixes changes to TinyMCE views in 4.2 - re https://github.com/fusioneng/Shortcake/issues/181

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Can we keep 4.1 code in for compat?

**Comment by mattheu** [comment]
Yeah - if we keep the old `View` property around - its fairly easy to support both simultaneously. Its a bit horrible though.

**Comment by danielbachhuber** [comment]
Let's do that for now

**Comment by danielbachhuber** [comment]
This seems to work pretty well, except it breaks Fusion Gallery preview for 4.2

**Comment by danielbachhuber** [comment]
I think the JavaScript is being stripped out

**Comment by mattheu** [comment]
> It breaks Fusion Gallery preview for 4.2

Fusion gallery was done first - the way I got the JS to initialize wasn't as neat as how you did if later - using the action to load the scripts. I have a PR ready to update this.

**Comment by danielbachhuber** [comment]
> I have a PR ready to update this.

Ok. If you can do on Monday, I can push to prod then.

**Comment by mattheu** [comment]
Current issues with this - that we would need to resolve before 4.2 drops, but I'd rather try and contribute fixes to core than build workarounds for this just yet.
- Styles aren't imported into the iframes automatically, and I'd rather not have to duplicate this functionaliyt from core. 
  - I've opened a ticket on trac - https://core.trac.wordpress.org/ticket/31464
  - Currently no styles are imported so some things look broken
- Sometimes iframe previews are not correctly resized to fit images. 
  - created a trac ticket for this also - https://core.trac.wordpress.org/ticket/31480

**Pull request merged**
