### PR TITLE
Make the dev plugin activatable on its own

### LINKED ISSUE #264: dev.php - Example shortcode.
We currently have dev.php that includes an example shortcode. Its great for pople getting started, as well as development.

The file just needs to be included. 
- It was brougt up in the chat this month that this could be enabled in the beta tester plugin.
- I keep committing this include by mistake ;)
  - daniel suggested a git pre commit hook.

Probably some improvements that can be made here.

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #264

### CODE REVIEW

**Comment by danielbachhuber** [comment]
image

**Comment by danielbachhuber** [comment]
@mattheu #reviewmerge

**Comment by mattheu** [comment]
Not necessarily part of this ticket - so happy to merge. But do you think we should exclude this from the plugin available on WordPress.org?

**Comment by danielbachhuber** [comment]
> But do you think we should exclude this from the plugin available on WordPress.org?

Eh. Probably makes sense. But, if someone is already manually loading it, then we'll cause a fatal on upgrade. I don't suspect the risk is huge.

**Comment by mattheu** [comment]
Just a thought. Currently its a developer focused tool - people need to roll their own shortcodes and the example will be a huge help.

**Pull request merged**
