### PR TITLE
Run content through _wp_Nop

### PR DESCRIPTION
**Pull request by mattheu**
See #171

A few concerns here
- Should this always run or should we set a flag?
- Should we really be using _wp_Nop?
- Is this a situation where it would be good to have unit tests? Maybe we should start some.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
> Should this always run or should we set a flag?

I think we need to always run, or not run. Decisions not options ;)

> Should we really be using _wp_Nop?

I'm not convinced. Seems like we'd make the code more brittle by being dependent on `switchEditors`

> Is this a situation where it would be good to have unit tests?

Yep

**Comment by mattheu** [comment]
After doing some further testing - I think its fine to just always run this.

Agreed that we don't want to depend on switchEditors, _wp_Nop is a pretty hacky ~100 lines of regex that I don't really want to duplicate - and I guess that we would be able to support fewer edge cases.

I've written some simpler regex to do this - should be sufficient. I'll look into doing some tests for this before we merge though.

**Comment by danielbachhuber** [comment]
> Agreed that we don't want to depend on switchEditors

Can we make it fail gracefully then if the variable isn't there?

**Comment by mattheu** [comment]
Sure. I think if we go down the route of supporting the WP editor inside shortcake ui, and also nested shortcodes, we want this to be pretty robust and I'd rather lean on the built-in WP Core functionality where possible

**Comment by mattheu** [comment]
I've synced this up with master and added some of the things we discussed.

However this is no longer working with WP trunk. The problem is that MCE views no longer  work at all if the shortcode content has HTML. I think this broke here: https://github.com/WordPress/WordPress/commit/b799bd8e3385373a823df72f472a23a501f694e2

I'll look into how feasable this is to support.

**Comment by mattheu** [comment]
Support for HTML and line breaks just got fixed in core. See https://core.trac.wordpress.org/changeset/32678 

A somewhat simpler solution to https://github.com/fusioneng/Shortcake/pull/322 - although it only works for the inner content, and not data stored in attributes.

I think this should go in regardless of #322, and we can review whether we need to extend support for HTML to all attributes.

**Pull request merged**
