### PR TITLE
Fix noconflict

### PR DESCRIPTION
**Pull request by mattheu**
cc @sanchothefat @danielbachhuber.

https://github.com/fusioneng/Shortcake/pull/232 does fix the problem and I don't think we need change this with any urgency. However I don't think it fixes the real issue.

The problem is not that we're using the global, either `$` or `jQuery`. The correct solution is to properly require jQuery and assign it to $. 

The copy of jQuery used in the tests calls `jQuery.noConflict()`. Just need more test coverage!

### CODE REVIEW

**Comment by danielbachhuber** [comment]
> Just need more test coverage!

Always the answer to everything :)

**Comment by roborourke** [comment]
@mattheu the copy of jquery shipped with WP is the same and has the noConflict call too. Will have a look at how to test for it properly

**Comment by mattheu** [comment]
Fixed this up so it merges cleanly. This should all be good.

**Comment by danielbachhuber** [comment]
Looks good

**Pull request merged**
