### PR TITLE
Better UX for changing an attachment

### PR DESCRIPTION
**Pull request by davisshaver**
See https://github.com/fusioneng/Shortcake/issues/350

### CODE REVIEW

**Comment by davisshaver** [comment]
@goldenapples Seemed almost too easy, what would you add?

**Comment by goldenapples** [comment]
:100: 

It seems like a hover state on the thumbnail div might be nice too, to aid in discoverability. I'd try an overlay or something?

**Comment by davisshaver** [comment]
Thanks @goldenapples, good idea. I added a light overlay to the image on hover to aid in discoverability. Right now it's `rgba( 0,0,0,.1)`, I could see us bumping that up maybe but I wasn't sure.

aug 05 2015 07 41

**Comment by goldenapples** [comment]
Nice! I like this look, and the experience is really smooth...

**Pull request merged**
