### PR TITLE
Refactor preview to prevent IE11 crashes

### PR DESCRIPTION
**Pull request by mattheu**
Shortcake crashes IE11 - https://github.com/fusioneng/Shortcake/issues/140

I narrowed it down to the preview - and I think the way it builds the iFrame. I wasn't that familiar with this bit of code so I dug into it a little bit. I ended up refactoring it a little bit.
- Use jQuery to build the iFrame instead of standard JS - since we're already using it.
- Removes need for template
- Now the code is much simpler - I think we can remove the iFrame constructor class.
- Use wp.ajax to fetch shortcode.

This fixes the IE11 crash

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@mattheu I get some errors:

image

Can you reproduce? Looks pretty good otherwise.

**Comment by mattheu** [comment]
Merged with master and fixed a small error - however this was a different error from what you are seeing.

I tried in a few browsers, and on a couple of projects - and couldn't replicate your exact errors.

If you're still seeing this - would be good if you could you give me a bit more info.

**Comment by danielbachhuber** [comment]
@mattheu were you able to fix the error?

**Comment by mattheu** [comment]
I was unable to reproduce. I'll look into it some more today.

**Comment by danielbachhuber** [comment]
I can't reproduce now. Let's ship to production and see if any users report.

**Pull request merged**
