### PR TITLE
Remove preview tab from Shortcake

### PR DESCRIPTION
**Pull request by davisshaver**
See https://github.com/fusioneng/Shortcake/issues/384

### CODE REVIEW

**Comment by davisshaver** [comment]
screen shot 2015-08-04 at 1 08 25 pm

One question I have regards the tabbed abstraction that got introduced in https://github.com/fusioneng/Shortcake/pull/61/files. This is a nice abstraction and I could see some short code implementations extending it for non-preview purposes. 

Opinions for/against a refactor to _remove_ tabbed abstraction?

**Comment by davisshaver** [comment]
@danielbachhuber Would you tackle anything else in the scope of the PR?

**Comment by danielbachhuber** [comment]
> This is a nice abstraction and I could see some short code implementations extending it for non-preview purposes.

Can you clarify?

> Would you tackle anything else in the scope of the PR?

Doesn't it make sense to remove the tab UI entirely? e.g. the "Edit" tab

**Comment by davisshaver** [comment]
Ok I will remove

**Comment by davisshaver** [comment]
Updated

screen shot 2015-08-04 at 1 27 02 pm

**Comment by danielbachhuber** [comment]
@davisshaver fyi ceb44030e15c93e6edef33be27fca56223160ebf

**Comment by davisshaver** [comment]
@danielbachhuber Dang thanks, I thought I grabbed that but guess not..

**Pull request merged**
