### PR TITLE
Update links in the readme to their new URLs

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #533

### CODE REVIEW

**Comment by goldenapples** [comment]
I believe Github URLs are case-sensitive, so we'll also have to change `Shortcake` to `shortcake` in those links.

**Comment by danielbachhuber** [comment]
> I believe Github URLs are case-sensitive

Nope https://github.com/wp-shortcake/Shortcake/wiki/Registering-Shortcode-UI

**Comment by danielbachhuber** [comment]
I'll update though

**Comment by goldenapples** [comment]
Ah, cool to know. I could swear I just tried to visit one of the links and got a 404. Must've mistyped it.

**Pull request merged**
