### PR TITLE
Added jshint

### PR DESCRIPTION
**Pull request by noppanit**
https://github.com/fusioneng/Shortcake/issues/295

### CODE REVIEW

**Comment by noppanit** [comment]
@mattheu potential bug? https://github.com/fusioneng/Shortcake/blob/master/js/src/field-post-select.js#L89

https://github.com/fusioneng/Shortcake/blob/master/js/src/views/shortcode-preview.js#L172 Not sure what this one is doing?

This one as well. https://github.com/fusioneng/Shortcake/blob/master/js/src/views/tabbed-view.js#L116

**Comment by mattheu** [comment]
Looks great. Thanks @noppanit. I'm just going to look into those issues you've flagged.

**Comment by noppanit** [comment]
Thanks @mattheu let me know if you need me to change anything.

**Comment by mattheu** [comment]
No I think this is all good. Flags some wierd code - but I don't think they're neccesarily bugs. Might be nice to clean up the code. Will merge once we've got v0.3.0 out the door.

**Comment by noppanit** [comment]
@mattheu actually I just realise that we don't have Travis for this project.

**Comment by noppanit** [comment]
@mattheu How do you want me to proceed on this? Do you want me to create Travis for this as well?

**Comment by mattheu** [comment]
Yeah definitely add it to travis I think

**Comment by davisshaver** [comment]
@noppanit how is this one going? want me to take it over finish next week?

**Comment by noppanit** [comment]
If you have some bandwidth please go ahead, but if not don't worry about it. Thanks very much @davisshaver

**Comment by danielbachhuber** [comment]
Closing in favor of #430

**Pull request closed without merging**
