### PR TITLE
Support for unquoted attributes

### LINKED ISSUE #241: Attribute values without quotation marks are ignored
A shortcode like:

`[testcode attr=yes]`

fails to parse the value of the attribute as it is not enclosed in quotation marks (ie. `[testcode attr="yes"]`).

The problem is on line 158 of shortcode-view-constructor.js:

`attributeMatches = matches[2].match( /(\S+?=".*?")/g ) || [];`

".*?" restricts the match to only attributes with quotation marks around their values.

### PR DESCRIPTION
**Pull request by mattheu**
Updated PR from toolstack - #249
- Added tests for unquoted attributes.
- Tests were failing attribute names that have a dash in them.
- Simplified regex and fixed failing tests.

This should be good to go. Thanks @toolstack

Notes 
- unquoted attributes CANNOT have spaces in them. This is consistent with core anyway.
- Unquoted attributes are converted to quoted attributes when you update them. I think this is reasonable. 

Fixes #241

### CODE REVIEW

**Comment by toolstack** [comment]
Just a note that the regex I used was pulled directly from core, so anything it matches is supported in core.

**Comment by mattheu** [comment]
Ah - maybe core doesn't support dashes in shortcodes then. I'll test this now

**Comment by mattheu** [comment]
> Just a note that the regex I used was pulled directly from core, so anything it matches is supported in core.

OK - we had a test that passes for dashes in attribute names - but you're right that this isn't supported in core.

I think its a good call to use the regex from core. Our test for this shouldn't pass. 

I've updated my PR

**Comment by mattheu** [comment]
Should be good to merge

**Comment by danielbachhuber** [comment]
:+1: looks good.

**Pull request merged**
