### PR TITLE
Bump version to 0.7.0

### PR DESCRIPTION
**Pull request by goldenapples**
Starting this branch to cover the new release bump.

So far, I've added a release notes section. 

Still need to:

- [x] review the contributors list and see if there's anyone who's missed
- [x] write up a full release post
...

### CODE REVIEW

**Comment by goldenapples** [comment]
Draft of a release post (still in progress) is here: https://docs.google.com/document/d/1kFXaI51HwVtGkpDwXcufwcihQ7q1lrpf1W1zKlQMLQY/edit?usp=sharing

Lets give that a read over, and then we can tag and release this version once we merge this PR.

**Comment by khromov** [comment]
Very well written!

**Comment by BronsonQuick** [comment]
I just had a read of the release post. Excellent work as always @goldenapples!

**Comment by mattheu** [comment]
Looks great. Thanks @goldenapples!

**Comment by goldenapples** [comment]
🚀

**Pull request merged**
