### PR TITLE
Update icon positioning, height of icon container and title

### PR DESCRIPTION
**Pull request by isGabe**
See #477

### CODE REVIEW

**Comment by isGabe** [comment]
This is what these changes would look like now, before landing the icon consistent work being done in https://github.com/fusioneng/shortcake-bakery/issues/95

screenshot 2015-09-30 17 11 50

**Comment by danielbachhuber** [comment]
@FStop looks pretty solid. ready for it to land?

**Comment by isGabe** [comment]
@danielbachhuber yep, I think it's good to go. #reviewmerge

**Comment by khromov** [comment]
@FStop @danielbachhuber Looks like this PR hides text overflow if it's more than one line. Example:

screen shot 2015-10-01 at 17 09 20

screen shot 2015-10-01 at 17 09 17

**Comment by danielbachhuber** [comment]
> Looks like this PR hides text overflow if it's more than one line.

What if we did horizontal scroll instead?

**Comment by khromov** [comment]
@danielbachhuber Horizontal scroll inside each icon? In that case I'd prefer that the "name badge" grew form the bottom and upwards like it did before, even if that means that the icon won't be perfectly positioned.

**Comment by isGabe** [comment]
@khromov @danielbachhuber Hmm yep, probably a result of adding a `height` to that element. We could probably do `min-height` instead...I can  open a new PR taking multiline text into account later today.

Horizontal scrolling is an interesting idea, but scrollbars on an element that small would probably be brutal.

**Comment by khromov** [comment]
Sounds like a good idea to add `min-height` @FStop !

**Pull request merged**
