### PR TITLE
Update to Select2 4.0.3

### PR DESCRIPTION
**Pull request by goldenapples**
See #646 

Still needs some work to initialize selected items when opening the shortcode modal, but is mostly functional otherwise.

### CODE REVIEW

**Comment by goldenapples** [comment]
This is fully functional now. I'll give it another pass and refactor out some of the duplicate code later...

**Comment by goldenapples** [comment]
@wp-shortcake/maintainers This is ready for a review & merge for potential inclusion with a 0.7.0 release.

It updates the Select2 version in use to 4.0.3, which should offer better compatability with other plugins (Customize Posts in particular). It also refactors all of the Ajax-enabled Select2 fields (Post Select, Term Select, and User Select) to extend a common Backbone view, so that the functionality which is common to all of these fields can more easily be updated.

**Comment by mattheu** [comment]
I've done some testing on this, mostly works great. 

I spotted a couple of bugs which I have fixed here https://github.com/wp-shortcake/shortcake/pull/655 and can be merged into this PR.

Also added a bit of styling in this PR: https://github.com/wp-shortcake/shortcake/pull/656

**Comment by goldenapples** [comment]
I've merged in the fixes from #655 and #656, and fixed the merge conflict with master. Ready for a final review/merge...

**Comment by mattheu** [comment]
OK lets go ahead and merge this one. It will be good to wrap up the 0.7.0 milestone!

**Pull request merged**
