### PR TITLE
Attributes without quotes and extra template options

### PR DESCRIPTION
**Pull request by toolstack**
- Attributes without quotation marks are parsed correctly.
- New template options to control the size, rows, cols of the input fields.
- New template option for required fields to add an asterisk after the label (should probably add some javascript to block the update call without having values).

### CODE REVIEW

**Comment by bfintal** [comment]
As discussed in #144, instead of handling specifically these additional attributes, we should just handle all attributes as in PR #212 

+1 for unquoted attributes

**Comment by danielbachhuber** [comment]
> Attributes without quotation marks are parsed correctly.

Can you break this into a separate PR please, and make sure to add test coverage?

@bfintal Apologies for the tardiness on your PRs. I'm back to 100% next week, and I'll dive into them then.

**Comment by toolstack** [comment]
I can break it out in to separate PR's, but I'm not familiar with building test coverage.

**Comment by danielbachhuber** [comment]
Continued in #249

**Pull request closed without merging**
