### PR TITLE
Addresses #392 - importing the WordPress shortcode regex

### PR DESCRIPTION
**Pull request by nikolov-tmw**
Fixes the issue where the inner content would be partially or fully truncated when editing a shortcode that contains another shortcode.

Without the fix:

Shortcode preview in rich text

Last part "amet." is missing from the Content.
"amet." missing

With the fix:

Full content is preserved

Below is a minimal plugin that allows you to replicate the issue and the fix. We have one shortcode( **simple** ) that just runs the content through `do_shortcode()` and another one that just puts the content in `<b></b>` tags( **b** ). 

```
<?php
/**
 * Plugin Name: Shortcodes Test
 */

function sct_init() {
    add_shortcode( 'simple', 'sct_simple_shortcode' );

    add_shortcode( 'b', 'sct_b_shortcode' );

    if ( function_exists( 'shortcode_ui_register_for_shortcode' ) ) {
        shortcode_ui_register_for_shortcode(
            'simple',
            array(
                'label'         => 'Plain Content',
                'listItemImage' => 'dashicons-welcome-write-blog',
                'inner_content' => array(
                    'label' => 'Content',
                ),
                'attrs'         => array(),
            )
        );
    }

}
add_action( 'init', 'sct_init', 10 );

function sct_simple_shortcode( $atts, $content = null ) {
    extract( shortcode_atts(array(), $atts, 'simple' /* Shortcode name for attribute filtering */ ) );

    return do_shortcode( $content );
}

function sct_b_shortcode( $atts, $content = null ) {
    extract( shortcode_atts(array(), $atts, 'b' /* Shortcode name for attribute filtering */ ) );

    return '<b>' . $content . '</b>';
}
```

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@nikolov-tmw This would really benefit from test coverage. Would you be willing to add it?

**Comment by nikolov-tmw** [comment]
Not sure how to do that :eyes: I haven't really written any JS tests before.
I'm also not sure what we should test for - make sure the content remains intact with and without shortcodes(with shortcodes with/without attributes). Anything else?

**Comment by danielbachhuber** [comment]
> Not sure how to do that :eyes: I haven't really written any JS tests before.

@noppanit can correct me if I'm wrong, but I think https://github.com/fusioneng/Shortcake/blob/master/js-tests/src/shortcodeModelSpec.js is a good place for it. He's written up some documentation here: https://github.com/fusioneng/tech-docs/blob/d47d1852d364a6dcae083e597658d289a22f17d8/wordpress-development/javascript-tests.md

> make sure the content remains intact with and without shortcodes(with shortcodes with/without attributes)

Yep, that'd be good. Generally, testing "both sides" of a bug is good practice.

**Comment by nikolov-tmw** [comment]
@danielbachhuber @noppanit - I see what the tests look like and it seems fairly easy to add new tests. However I wanted to ask if I should create a different instance of `Shortcode()` for every different content test.

Because a good place for the new tests would be inside of the 'Inner content set correctly..' section.

Or should I just add for instance

`shortcode.set( 'inner_content', 'test content [test]with shortcodes[/test]' )`

And then do

`expect( shortcode.get( 'inner_content' ).get('value')...`

**Comment by danielbachhuber** [comment]
> However I wanted to ask if I should create a different instance of Shortcode() for every different content test.

You can just reuse the existing model.

**Comment by khromov** [comment]
@nikolov-tmw There seems to be an issue if you nest a shortcode that is also registered in Shortcake. Shortcodes that are not registered in Shortcake work fine when you nest them, but if they are registrered in Shortcake everything breaks.

**Comment by danielbachhuber** [comment]
This was landed in #487

**Pull request closed without merging**
