### PR TITLE
Add German translation

### PR DESCRIPTION
**Pull request by scherii**
First draft of German translation

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@scherii Let me know when you're ready to have these merged?

**Comment by danielbachhuber** [comment]
@goldenapples let's go ahead and land this

**Comment by goldenapples** [comment]
Ugh, wait. I merged this without looking it over thoroughly. Will a file named `shortcode-ui-de.po` actually get loaded? Shouldn't it be named after a specific locale, like `shortcode-ui-de_DE.po`?

@scherii @danielbachhuber ?

**Comment by scherii** [comment]
I'm sorry, I forgot about this.

According to [WordPress' Codex](http://codex.wordpress.org/I18n_for_WordPress_Developers#Loading_a_Text_Domain) it should:

> The locale is the language code and/or country code you defined in the constant WPLANG in the file wp-config.php. For example, the locale for German is 'de', and the locale for Danish is 'da_DK'.

_Edit: Haven't read the top part of this article. [This version](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#loading-text-domain) seems more up to date._

But I just tested it and with my `de_CH` locale (and `de_DE` fallback provided by [2ndkauboy](https://github.com/2ndkauboy/language-fallback)) – it didn't work.

I just created `de_DE` (PR follows) and it works.

**Pull request merged**
